#!/bin/sh
# Generated by research-repo-tools toolchain bootstrap. Regenerate after changing the uv pin.
set -eu
rrt_uv_version='__UV_VERSION__'
rrt_cache=${RESEARCH_REPO_TOOLS_HOME:-"$HOME/.cache/research-repo-tools"}
case "$rrt_cache" in /*) ;; *) echo 'RESEARCH_REPO_TOOLS_HOME must be absolute' >&2; exit 1 ;; esac
rrt_uv="$rrt_cache/uv/$rrt_uv_version/uv"
rrt_has_version() {
    rrt_output=$("$1" --version) || return 1
    case "$rrt_output" in "uv $rrt_uv_version"|"uv $rrt_uv_version "*) return 0 ;; *) return 1 ;; esac
}
if [ ! -e "$rrt_uv" ] && command -v uv >/dev/null 2>&1 && rrt_has_version uv; then
    rrt_uv=$(command -v uv)
elif ! rrt_has_version "$rrt_uv" 2>/dev/null; then
    command -v curl >/dev/null 2>&1 || { echo 'Install curl to bootstrap uv.' >&2; exit 1; }
    rrt_installer=$(mktemp)
    trap 'rm -f "$rrt_installer"' 0
    trap 'exit 129' HUP
    trap 'exit 130' INT
    trap 'exit 143' TERM
    curl --proto '=https' --tlsv1.2 --fail --show-error --silent --location \
        --connect-timeout 30 --max-time 300 "https://astral.sh/uv/$rrt_uv_version/install.sh" -o "$rrt_installer"
    UV_UNMANAGED_INSTALL="$rrt_cache/uv/$rrt_uv_version" UV_NO_MODIFY_PATH=1 sh "$rrt_installer" >&2
    rrt_has_version "$rrt_uv" || { echo 'uv installation failed version verification.' >&2; exit 1; }
fi
if [ "${1:-}" = '--uv-only' ]; then
    printf '%s\n' "$rrt_uv"
    exit 0
fi
if [ "$#" -ne 0 ]; then echo 'Usage: sh bootstrap.sh' >&2; exit 2; fi
rrt_root=$(CDPATH='' cd -- "$(dirname -- "$0")" && pwd)
cd "$rrt_root"
PATH="$(dirname -- "$rrt_uv"):$PATH"
export PATH
"$rrt_uv" run --locked --managed-python --only-group tooling research-repo-tools toolchain sync
"$rrt_uv" run --locked --managed-python --only-group tooling research-repo-tools toolchain run -- uv sync --locked --managed-python --group tooling
