# Generated by research-repo-tools toolchain bootstrap. Regenerate after changing the uv pin.
param([switch]$UvOnly)
$ErrorActionPreference = 'Stop'
$rrtUvVersion = '__UV_VERSION__'
$rrtCache = $env:RESEARCH_REPO_TOOLS_HOME
if (-not $rrtCache) { $rrtCache = Join-Path $HOME '.cache/research-repo-tools' }
if ($rrtCache -notmatch '^(?:[A-Za-z]:[\\/]|[\\/]{2}[^\\/]+[\\/][^\\/]+)') { throw 'RESEARCH_REPO_TOOLS_HOME must be absolute' }
$rrtUv = Join-Path $rrtCache "uv/$rrtUvVersion/uv.exe"
function Test-RrtUvVersion([string]$Executable) {
    if (-not (Test-Path -LiteralPath $Executable -PathType Leaf)) { return $false }
    $rrtOutput = & $Executable --version
    return ($LASTEXITCODE -eq 0 -and $rrtOutput -match ('^uv ' + [regex]::Escape($rrtUvVersion) + '(\s|$)'))
}
$rrtExisting = Get-Command uv -CommandType Application -ErrorAction SilentlyContinue
if (-not (Test-Path -LiteralPath $rrtUv) -and $rrtExisting -and (Test-RrtUvVersion $rrtExisting.Source)) {
    $rrtUv = $rrtExisting.Source
} elseif (-not (Test-RrtUvVersion $rrtUv)) {
    $rrtInstaller = Join-Path ([IO.Path]::GetTempPath()) ([guid]::NewGuid().ToString() + '.ps1')
    $rrtOldInstall = $env:UV_UNMANAGED_INSTALL
    $rrtOldPathPolicy = $env:UV_NO_MODIFY_PATH
    try {
        Invoke-WebRequest -Uri "https://astral.sh/uv/$rrtUvVersion/install.ps1" -OutFile $rrtInstaller -TimeoutSec 300
        $env:UV_UNMANAGED_INSTALL = Join-Path $rrtCache "uv/$rrtUvVersion"
        $env:UV_NO_MODIFY_PATH = '1'
        & powershell.exe -NoProfile -ExecutionPolicy Bypass -File $rrtInstaller
        if ($LASTEXITCODE -ne 0) { throw 'uv installer failed' }
        if (-not (Test-RrtUvVersion $rrtUv)) { throw 'uv installation failed version verification' }
    } finally {
        $env:UV_UNMANAGED_INSTALL = $rrtOldInstall
        $env:UV_NO_MODIFY_PATH = $rrtOldPathPolicy
        Remove-Item -LiteralPath $rrtInstaller -Force -ErrorAction SilentlyContinue
    }
}
if ($UvOnly) { Write-Output $rrtUv; exit 0 }
$rrtOldPath = $env:PATH
Push-Location -LiteralPath $PSScriptRoot
try {
    $env:PATH = (Split-Path -Parent $rrtUv) + [IO.Path]::PathSeparator + $rrtOldPath
    & $rrtUv run --locked --managed-python --only-group tooling research-repo-tools toolchain sync
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
    & $rrtUv run --locked --managed-python --only-group tooling research-repo-tools toolchain run -- uv sync --locked --managed-python --group tooling
    exit $LASTEXITCODE
} finally {
    $env:PATH = $rrtOldPath
    Pop-Location
}
